
from cgi import print_environ
import time
import random
from  colorama import Fore, Back, Style
import os
from os import system, name

os.system('color 9')

print("    ________________$$$$$$$$ ") 
print("________________$$$$$$$$$$$$") 
print("______________$$$$$$$$$$$$$$$$") 
print("______________$$$$$$$$$$ 🔴 $$$$§§§§§§§§") 
print("______________$$$$$$$$$$$$$$$$") 
print("______________$$$$$$$$$$$$$$$$§§$§§§") 
print("______________$$$$$$$$$$$$$$") 
print("____ ____________$$$$$$$$") 
print("__________________$$$$$$$") 
print("__________________ __$$$$$$") 
print("_____________________$$$$$$$") 
print("______________________$$$$$$$ $") 
print("______________________$$$$$$$$$$") 
print("_____________________$$$$$$$$$$$$") 
print("________________s$$$$$$$__$$$$$$$$$$") 
print("_____________s$$$$$$$$$$__$$$$$$$$$$") 
print("____________$$$$§§§§§§§§__$$$$$$$$$$") 
print("_________s$$$$§§§§§§§ §§§__$$$$$$$$$") 
print("$$____$$$$$$§§§§§§§§§§__$$$$$$$$$$") 
print("$$$$$$$$$$$$§§? ?§§§§§__$$$$$$$$$$s") 
print("$$$$$$$$$$$$$$$$$$$__$$$$$$$$$s") 
print("$$$$$$$$$$$$$$$$$$$$$$$ $$$$$ ______§§__§§§§") 
print("__$$$$$$$$$$$$$$$$$$$$$$$$s_______§§§§§§") 
print("____$$$$$$$$ $$$$$$$$$$$$$$________§§§§") 
print("______$$$$$$$$$$$$$$$$__§§________§§") 
print("________ __$$$$$$$$______§§§§§§§§§§") 
print("________§§§§") 
print("________§§") 
print("________§§") 
print("__________§§§§§§§§ ") 
print("") 
print("Bienvenu(e) sur DuckDoxer™ 🦆") 

print("\033[1;37;40m")
ip_ddos = input("📡 Entrer l'IP que vous voulez DDoS : ")

paquet_send = input("📦 Entrer le nombre de Packet à envoyer : ")

zeubdanslcul = input(' ♦ Attack in Man In The Middle.')


1
os.system('color 4')
print("[*] Loading [                ]")
time.sleep(1)
print("[*] Loading [==              ]")
time.sleep(1.5)
print("[*] Loading [===             ]")
time.sleep(5)
print("[*] Loading [====            ]")
time.sleep(1)
print("[*] Loading [=====           ]")
time.sleep(0.5)
print("[*] Loading [======          ]")
time.sleep(2)
print("[*] Loading [=======         ]")
time.sleep(2)
print("[*] Loading [========        ]")
time.sleep(1.5)
print("[*] Loading [=========       ]")
time.sleep(1)
print("[*] Loading [==========      ]")
time.sleep(1.5)
print("[*] Loading [===========     ]")
time.sleep(1)
print("[*] Loading [============    ]")
time.sleep(1.5)
print("[*] Loading [=============  ]")
time.sleep(6)
print("[*] Loading [=============== ]")
time.sleep(1)
print("\033[1;31;40m")
time.sleep(0.3)
os.system('color a')
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(1)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(1)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(1)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(1)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(0.5)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(0.5)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(0.5)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(0.5)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(0.5)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(0.5)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(0.5)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(1)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(1)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(1)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(1)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(0.5)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(0.5)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(0.5)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(0.5)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(0.5)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(0.5)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(0.5)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(1)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(1)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(1)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(1)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(0.5)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(0.5)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(0.5)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(0.5)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(0.5)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(0.5)
print("=> Envoi 📥 : 70Mo to [" +ip_ddos+"] - [ Recept paquet 0x417841855: [= Recevied 0.1 ms TCP ] | Connection Out of 570ms.STC ]")
time.sleep(0.5)


print(" ")
print("-----------------💀 IP DOWN 💀-----------------")
time.sleep(2.5)
print(" ")
print("🔂 IP down => Ping: 547ms " + ip_ddos)
print("⚠ Si le programme se relance pas, alors sa Box est DOWN. ⚠ ")
time.sleep(1)
